# Generated by Django 3.1.3 on 2021-02-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('check', models.PositiveIntegerField(choices=[(1, 'VALIDITY'), (2, 'HTTPOK')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
