# Generated by Django 3.1.3 on 2021-01-31 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('runners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('check', models.PositiveIntegerField(choices=[(1, 'VALIDITY'), (2, 'HTTPOK')], default=None)),
                ('runner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='runners.runnersmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
