# Generated by Django 3.1.3 on 2021-02-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkersmodel',
            name='runner',
        ),
        migrations.AlterField(
            model_name='checkersmodel',
            name='check',
            field=models.PositiveIntegerField(choices=[(1, 'VALIDITY'), (2, 'HTTPOK')], default=1),
        ),
    ]
