# Generated by Django 3.1.3 on 2021-01-31 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0001_initial'),
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesmodel',
            name='runner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='runners.runnersmodel'),
        ),
        migrations.AddField(
            model_name='websitesmodel',
            name='url',
            field=models.TextField(default='https://google.com', editable=False, verbose_name='Url du site à inspecter'),
        ),
    ]
