# Generated by Django 3.1.3 on 2021-02-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_auto_20210131_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesmodel',
            name='runner',
        ),
        migrations.AlterField(
            model_name='websitesmodel',
            name='name',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='Nom du site à inspecter'),
        ),
        migrations.AlterField(
            model_name='websitesmodel',
            name='url',
            field=models.TextField(default='https://google.com', verbose_name='Url du site à inspecter'),
        ),
    ]
