# Generated by Django 3.1.3 on 2021-02-01 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websites', '__first__'),
        ('checkers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('isSuccess', models.BooleanField(default=False)),
                ('checkers', models.ManyToManyField(blank=True, to='checkers.CheckersModel')),
                ('websites', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.websitesmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
