# Generated by Django 3.1.3 on 2021-02-01 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_auto_20210201_0822'),
        ('checkers', '0002_auto_20210201_0822'),
        ('runners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnersmodel',
            name='checkers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkers.checkersmodel'),
        ),
        migrations.AddField(
            model_name='runnersmodel',
            name='websites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='websites.websitesmodel'),
        ),
    ]
